on:
  workflow_dispatch:

name: Publish Documentation
jobs:
  build-publish-docs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed if using OIDC to get release secrets.
      contents: write # Needed in this case to write github pages.
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install poetry
        run: pipx install poetry

      - uses: ./.github/actions/build-docs

      - uses: ./.github/actions/publish-docs
        with:
          token: ${{secrets.GITHUB_TOKEN}}
