on:
  workflow_dispatch:

name: Publish Documentation
jobs:
  build-publish-docs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed if using OIDC to get release secrets.
      contents: write # Needed in this case to write github pages.
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: "3.10"

      - uses: ./.github/actions/build-docs

      - uses: ./.github/actions/publish-docs
        with:
          token: ${{secrets.GITHUB_TOKEN}}
