name: Run Release Please

on:
  push:
    branches:
      - main

jobs:
  release-package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed if using OIDC to get release secrets.
      contents: write # Contents and pull-requests are for release-please to make releases.
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          fetch-depth: 0 # If you only need the current version keep this.

      - uses: actions/setup-python@v4
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          python-version: 3.9

      - name: Install poetry
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: abatilo/actions-poetry@7b6d33e44b4f08d7021a1dee3c044e9c253d6439

      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
        name: "Get PyPI token"
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: "/production/common/releasing/pypi/token = PYPI_AUTH_TOKEN"

      - uses: ./.github/actions/build
        if: ${{ steps.release.outputs.releases_created == 'true' }}

      - uses: ./.github/actions/build-docs
        if: ${{ steps.release.outputs.releases_created == 'true' }}

      - name: Publish package distributions to PyPI
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{env.PYPI_AUTH_TOKEN}}
